CORE_DIR = $(PROJ_FILES)/kernel/src/arch/cores/$(ARCH)

CFLAGS += -I$(CORE_DIR)
CFLAGS += -I$(CORE_DIR)/C

# C core content is only in BSP by now (not in userspace drivers)
core-bsp-y :=

# configurable

# per app
# no need for FPU for loader
core-bsp-$(CONFIG_FPU_ENABLE) += C/m4-fpu.c

core-ada-bsp-y :=
# for Ada equivalent

core-ada-bsp-y += Ada/m4-mpu.adb
core-ada-bsp-y += Ada/m4-systick.adb

