------------------------------------------------------------------------
----      Copyright (c) 15-01-2018, ANSSI
----      All rights reserved.
----
---- This file is autogenerated by tools/gen_ld.pl
----
---- This file describes the applications layout and permissions for
---- the current build.
---- Please see the above script for details.
----
--------------------------------------------------------------------------

--
-- This file is autogenerated ! Don't try to update it as it is
-- regenerated each time the kernel is built !
--

with interfaces;        use interfaces;
with types;             use types;
with ewok.tasks_shared; use ewok.tasks_shared;
with ewok.tasks;	    use ewok.tasks;

package applications is

   type t_application is record
      -- task name
      name              : ewok.tasks.t_task_name;
      -- task text section addr in flash
      text_addr         : system_address;
      -- task text size, in bytes
      text_size         : system_address;
      -- task data address, in RAM
      data_addr         : system_address;
      -- task data size
      data_size         : system_address;
      -- task BSS size
      bss_size          : system_address;
      -- task requested stack size
      stack_size        : system_address;
      -- entrypoint offset, starting at text_addr
      entrypoint_off    : system_address;
      -- isr_entrypoint offset, starting at text_addr
      isr_entrypoint_off: system_address;
      -- task security domain
      domain            : unsigned_8;
      -- task priority
      priority          : unsigned_8;
   end record;


   -- list of activated applications
   subtype t_real_task_id is t_task_id
