BOARD_DIR = $(PROJ_FILES)/kernel/arch/boards/$(BOARD)

CFLAGS += -I$(BOARD_DIR)
CFLAGS += -I$(BOARD_DIR)/..

board-bsp-y :=

# per-board drivers
ifneq ($(BOARD),)
include $(PROJ_FILES)kernel/arch/boards/$(BOARD)/Makefile.objs
endif
